language: php

sudo: false

cache:
  directories:
  - vendor

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  
matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - phpunit --coverage-text --verbose --coverage-clover=coverage.clover --coverage-html coverage